name = "glome"
version = "0.3.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library to write and run Home Assistant automations."
repository = { type = "github", user = "dennisschroeder", repo = "glome" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.22"
nerf = "~> 0.1"
gleam_otp = "~> 0.3"
gleam_httpc = "~> 1.1"
gleam_erlang = "~> 0.5 or ^0.27.0"
gleam_json = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.5"
