name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: 23.2
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: 0.21.0
      - run: gleam deps download
      - run: gleam test
